### PR TITLE
parallel apidoc

### PR DESCRIPTION
**Pull request by ebarboni**
maybe allow better build time 
just put the stage in parallel

used NetBeans formatter as to many curly bracket

### CODE REVIEW

**Comment by mbien** [comment]
this means that 
`stage ('Master build')`
and
`stage ('Release preparation')`
will run isolated from each other in parallel?

**Comment by mbien** [comment]
can you rename
https://github.com/apache/netbeans-jenkins-lib/blob/e3d9c65ee5c17fb27b390ab966997a8ee7ad708d/vars/asfMainNetBeansBuild.groovy#L301-L302
if this isn't parallel as the comment indicates?

**Comment by ebarboni** [comment]
> this means that `stage ('Master build')` and `stage ('Release preparation')` will run isolated from each other in parallel?

they are mutual exclusive per "branch", the most tricky maybe the 'Release preparation' and 'Release branch javadoc rebuild to nightlies'

**Comment by ebarboni** [comment]
closing as not really needed.

**Pull request closed without merging**
