### PR TITLE
run zip and unzip quietly.

### PR DESCRIPTION
**Pull request by mbien**
current log size is almost 70mb. A significant part of it are inflate/
deflate lines.

### CODE REVIEW

**Review by ebarboni — APPROVED** [review]

**Comment by mbien** [comment]
> I guess possible to merge now and trigger a release150 build to see gain in log. RC1 build is locked so it will be safe

in theory yes but the big fix however is still in the delivery queue https://github.com/apache/netbeans/pull/4410 which will be synced just before RC2, while #64 is already in this repo - this would break the build if it would run now, right?.

**Comment by ebarboni** [comment]
if we merge #65 we could see the gain in zip unzip quiet mode. if we merge #64 it will fail because we need the https://github.com/apache/netbeans/pull/4410 on release 150 but we have two fix at once so it will gain log but we don't know the source :D

**Comment by ebarboni** [comment]
build 7 Ignore 66,622 Ko. Log complet (before merging)
build 8 Ignore 65,122 Ko. Log complet (getmaven coordinate)
build 9 (to be edited)

**Comment by mbien** [comment]
@ebarboni excellent :)

**Comment by ebarboni** [comment]
@neilcsmith-net build is ok maven external are back to short list. RC2 should be ok on next week. thanks for merging in middle of week.

**Comment by neilcsmith-net** [comment]
Well, thanks @ebarboni and @mbien for looking at this!  Build times still seem higher than before, though.  Did you note the times for 7,8,9 too, as well as the log length?

**Comment by mbien** [comment]
comparing build 6 with 8:
https://ci-builds.apache.org/blue/organizations/jenkins/Netbeans%2Fnetbeans-TLP%2Fnetbeans/detail/release150/6/pipeline/
https://ci-builds.apache.org/blue/organizations/jenkins/Netbeans%2Fnetbeans-TLP%2Fnetbeans/detail/release150/8/pipeline/

all steps are a bit slower. different node?

**Comment by ebarboni** [comment]
this is not easy to compute. Build 7 - 9 where approx 2h10min in length.

maybe the mavenrepo could be one big zip instead of each artefacts.

**Pull request merged**
